apiVersion: apps/v1
kind: Deployment
metadata:
  name: tornado-app
  labels:
    app: tornado-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tornado-app
  template:
    metadata:
      labels:
        app: tornado-app
    spec:
      # Wait for Redis to become available before running the main app
      initContainers:
      - name: wait-for-redis
        image: busybox:1.36
        command: ['sh', '-c', 'until nc -z redis-service 6379; do echo "waiting for redis..."; sleep 2; done;']
      containers:
      - name: devops-demo
        image: us-central1-docker.pkg.dev/iti-project-477114/abdelaziz-gbr/tornado-app:latest
        ports:
        - containerPort: 8000
        env:
        - name: ENVIRONMENT
          value: "PROD"
        - name: HOST
          value: "0.0.0.0"
        - name: PORT
          value: "8000"
        - name: REDIS_HOST
          value: "redis-service"
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_DB
          value: "0"
        readinessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  type: LoadBalancer
  selector:
    app: tornado-app
  ports:
  - port: 80
    targetPort: 8000
